blank_issues_enabled: false
contact_links:
  - name: Questions / discussion
    url: https://github.com/nostr-net/archive-relay/discussions
    about: For usage questions and design discussion, please use Discussions.
